package edu.mum.volunteering.domain;
// Generated Sep 12, 2016 12:53:46 AM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "volunteering")
public class Project implements java.io.Serializable {

	private Integer projectId;
	private User user;
	private Integer description;
	private Date expectedStartDate;
	private Date expectedEndDate;
	private int status;
	private Set<Task> tasks = new HashSet<Task>(0);

	public Project() {
	}

	public Project(User user, int status) {
		this.user = user;
		this.status = status;
	}

	public Project(User user, Integer description, Date expectedStartDate, Date expectedEndDate, int status,
			Set<Task> tasks) {
		this.user = user;
		this.description = description;
		this.expectedStartDate = expectedStartDate;
		this.expectedEndDate = expectedEndDate;
		this.status = status;
		this.tasks = tasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "projectID", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdBy", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "description")
	public Integer getDescription() {
		return this.description;
	}

	public void setDescription(Integer description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expectedStartDate", length = 10)
	public Date getExpectedStartDate() {
		return this.expectedStartDate;
	}

	public void setExpectedStartDate(Date expectedStartDate) {
		this.expectedStartDate = expectedStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expectedEndDate", length = 10)
	public Date getExpectedEndDate() {
		return this.expectedEndDate;
	}

	public void setExpectedEndDate(Date expectedEndDate) {
		this.expectedEndDate = expectedEndDate;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
