package edu.mum.volunteering.domain;
// Generated Sep 12, 2016 12:53:46 AM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "volunteering")
public class Resource implements java.io.Serializable {

	private Integer resourceId;
	private int name;
	private Set<Task> tasks = new HashSet<Task>(0);

	public Resource() {
	}

	public Resource(int name) {
		this.name = name;
	}

	public Resource(int name, Set<Task> tasks) {
		this.name = name;
		this.tasks = tasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "resourceID", unique = true, nullable = false)
	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "name", nullable = false)
	public int getName() {
		return this.name;
	}

	public void setName(int name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
