package edu.mum.volunteering.domain;
// Generated Sep 12, 2016 12:53:46 AM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VolunteerOffer generated by hbm2java
 */
@Entity
@Table(name = "volunteer_offer", catalog = "volunteering")
public class VolunteerOffer implements java.io.Serializable {

	private Integer offerId;
	private Task task;
	private User user;
	private String service;

	public VolunteerOffer() {
	}

	public VolunteerOffer(Task task, User user) {
		this.task = task;
		this.user = user;
	}

	public VolunteerOffer(Task task, User user, String service) {
		this.task = task;
		this.user = user;
		this.service = service;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "offerID", unique = true, nullable = false)
	public Integer getOfferId() {
		return this.offerId;
	}

	public void setOfferId(Integer offerId) {
		this.offerId = offerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taskID", nullable = false)
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "service", length = 65535)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

}
