package edu.mum.volunteering.domain;
// Generated Sep 12, 2016 12:53:46 AM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "volunteering")
public class Image implements java.io.Serializable {

	private Integer imgId;
	private String name;
	private Set<Task> tasks = new HashSet<Task>(0);
	private Set<Beneficiary> beneficiaries = new HashSet<Beneficiary>(0);

	public Image() {
	}

	public Image(String name) {
		this.name = name;
	}

	public Image(String name, Set<Task> tasks, Set<Beneficiary> beneficiaries) {
		this.name = name;
		this.tasks = tasks;
		this.beneficiaries = beneficiaries;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "imgID", unique = true, nullable = false)
	public Integer getImgId() {
		return this.imgId;
	}

	public void setImgId(Integer imgId) {
		this.imgId = imgId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "image")
	public Set<Beneficiary> getBeneficiaries() {
		return this.beneficiaries;
	}

	public void setBeneficiaries(Set<Beneficiary> beneficiaries) {
		this.beneficiaries = beneficiaries;
	}

}
