package edu.mum.volunteering.domain;
// Generated Sep 12, 2016 12:53:46 AM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "task", catalog = "volunteering")
public class Task implements java.io.Serializable {

	private Integer taskId;
	private Image image;
	private Project project;
	private Resource resource;
	private User user;
	private String description;
	private Integer status;
	private Date dueDate;
	private Set<TaskBeneficiary> taskBeneficiaries = new HashSet<TaskBeneficiary>(0);
	private Set<VolunteerOffer> volunteerOffers = new HashSet<VolunteerOffer>(0);

	public Task() {
	}

	public Task(Project project) {
		this.project = project;
	}

	public Task(Image image, Project project, Resource resource, User user, String description, Integer status,
			Date dueDate, Set<TaskBeneficiary> taskBeneficiaries, Set<VolunteerOffer> volunteerOffers) {
		this.image = image;
		this.project = project;
		this.resource = resource;
		this.user = user;
		this.description = description;
		this.status = status;
		this.dueDate = dueDate;
		this.taskBeneficiaries = taskBeneficiaries;
		this.volunteerOffers = volunteerOffers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "taskID", unique = true, nullable = false)
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "imgID")
	public Image getImage() {
		return this.image;
	}

	public void setImage(Image image) {
		this.image = image;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectID", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resourceID")
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assignedTo")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dueDate", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<TaskBeneficiary> getTaskBeneficiaries() {
		return this.taskBeneficiaries;
	}

	public void setTaskBeneficiaries(Set<TaskBeneficiary> taskBeneficiaries) {
		this.taskBeneficiaries = taskBeneficiaries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
	public Set<VolunteerOffer> getVolunteerOffers() {
		return this.volunteerOffers;
	}

	public void setVolunteerOffers(Set<VolunteerOffer> volunteerOffers) {
		this.volunteerOffers = volunteerOffers;
	}

}
