package edu.mum.volunteering.domain;
// Generated Sep 12, 2016 12:53:46 AM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "volunteering")
public class User implements java.io.Serializable {

	private Integer userid;
	private UserRole userRole;
	private String username;
	private Byte enabled;
	private String fullname;
	private Integer gender;
	private String email;
	private String password;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Task> tasks = new HashSet<Task>(0);
	private Set<VolunteerOffer> volunteerOffers = new HashSet<VolunteerOffer>(0);

	public User() {
	}

	public User(UserRole userRole, String username) {
		this.userRole = userRole;
		this.username = username;
	}

	public User(UserRole userRole, String username, Byte enabled, String fullname, Integer gender, String email,
			String password, Set<Project> projects, Set<Task> tasks, Set<VolunteerOffer> volunteerOffers) {
		this.userRole = userRole;
		this.username = username;
		this.enabled = enabled;
		this.fullname = fullname;
		this.gender = gender;
		this.email = email;
		this.password = password;
		this.projects = projects;
		this.tasks = tasks;
		this.volunteerOffers = volunteerOffers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userid", unique = true, nullable = false)
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleID", nullable = false)
	public UserRole getUserRole() {
		return this.userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "enabled")
	public Byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Byte enabled) {
		this.enabled = enabled;
	}

	@Column(name = "fullname", length = 100)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "gender")
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 500)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<VolunteerOffer> getVolunteerOffers() {
		return this.volunteerOffers;
	}

	public void setVolunteerOffers(Set<VolunteerOffer> volunteerOffers) {
		this.volunteerOffers = volunteerOffers;
	}

}
